TEAM_MAPPINGS = {
    "Atlanta Utd": "Atlanta United",
    "Austin": "Austin FC",
    "CF Montréal": "CF Montreal",
    "Charlotte FC": "Charlotte",
    "Chicago Fire": "Chicago Fire",
    "Chivas USA": "Chivas USA",
    "Columbus Crew": "Columbus Crew",
    "Crew": "Columbus Crew",
    "D.C. United": "DC United",
    "Dynamo": "Houston Dynamo",
    "Dynamo FC": "Houston Dynamo",
    "FC Cincinnati": "FC Cincinnati",
    "FC Dallas": "FC Dallas",
    "Fire": "Chicago Fire",
    "Inter Miami CF": "Inter Miami",
    "LA Galaxy": "Los Angeles Galaxy",
    "LAFC": "Los Angeles FC",
    "Minnesota Utd": "Minnesota United",
    "Montreal Impact": "CF Montreal",
    "NE Revolution": "New England Revolution",
    "NY Red Bulls": "New York Red Bulls",
    "NYCFC": "New York City",
    "New York City FC": "New York City",
    "Nashville": "Nashville SC",
    "Orlando City": "Orlando City",
    "Orlando City SC": "Orlando City",
    "Philadelphia": "Philadelphia Union",
    "Portland Timbers": "Portland Timbers",
    "RSL": "Real Salt Lake",
    "Rapids": "Colorado Rapids",
    "SJ Earthquakes": "San Jose Earthquakes",
    "Seattle": "Seattle Sounders",
    "Seattle Sounders FC": "Seattle Sounders",
    "Sporting KC": "Sporting Kansas City",
    "St. Louis": "St. Louis City",
    "St. Louis City SC": "St. Louis City",
    "Toronto FC": "Toronto FC",
    "Vancouver W'caps": "Vancouver Whitecaps",
    "Vancouver Whitecaps FC": "Vancouver Whitecaps",
}
